spring:
  application:
    name: newbie-homework
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: '1234'
    url: 'jdbc:h2:mem:cathaybk'
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql