-- 貨幣資訊
CREATE TABLE CFG_CURRENCY_INFO (
    NO INT AUTO_INCREMENT PRIMARY KEY,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    CREATE_USER VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
    CFG_CURRENCY_INFO (CURRENCY_CODE, CREATE_USER, CREATED_AT, UPDATE_USER, UPDATED_AT)
VALUES
    ('USD', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    ('EUR', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    ('JPY', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    ('GBP', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    ('AUD', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP);

-- 貨幣名稱
CREATE TABLE MAP_CURRENCY_DESC (
    CURRENCY_NO INT PRIMARY KEY,
    CURRENCY_NAME VARCHAR(255) NOT NULL,
    CREATE_USER VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
    MAP_CURRENCY_DESC (CURRENCY_NO, CURRENCY_NAME, CREATE_USER, CREATED_AT, UPDATE_USER, UPDATED_AT)
VALUES
    (1, 'United States Dollar', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (2, 'Euro', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (3, 'Japanese Yen', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (4, 'British Pound', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (5, 'Australian Dollar', 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP);

-- 貨幣匯率
CREATE TABLE CUR_EXCHANGE_RATE (
    CURRENCY_NO INT PRIMARY KEY,
    EXCHANGE_RATE DECIMAL(10, 4) NOT NULL,
    CREATE_USER VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CUR_EXCHANGE_RATE
    (CURRENCY_NO, EXCHANGE_RATE, CREATE_USER, CREATED_AT, UPDATE_USER, UPDATED_AT)
VALUES
    (1, 27.5, 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (2, 29.41, 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (3, 0.29, 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (4, 33.41, 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP),
    (5, 21.01, 'Admin', CURRENT_TIMESTAMP, 'Admin', CURRENT_TIMESTAMP);